version: 2
jobs:
  build:
    working_directory: ~/graphql-cli-prepare
    docker:
      - image: circleci/node:latest@sha256:11ec281fcfb7c92a0492691459f6971cd4a41af67fedb4778a6a05922028ad0b
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g yarn@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-yarn
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: yarn test
      - run:
          name: release
          command: yarn semantic-release || true